#This file is the logging configuration file I use for logging in the project.
#More can be added as needed.

version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: '%(asctime)s %(name)s: %(levelname)s: %(message)s'
    datefmt: '%d/%m %H:%M:%S'
  detailed:
    format: '%(asctime)s %(name)s: %(levelname)s: %(message)s'
    datefmt: '%Y/%m/%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: WARNING
    formatter: simple
    #default stream is sys.stderr
    #stream: ext://sys.stderr

  ex_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: ../logs/ex.log
    maxBytes: 10000
    #backupCount: 0

  rh_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: ../logs/rh.log
    maxBytes: 10000 #max a little less than 10kb
    backupCount: 1

  db_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: ../logs/db.log
    maxBytes: 10000
    backupCount: 5

  test_handler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

loggers:
  rh_logger:
    level: DEBUG
    handlers: [console, rh_handler]
    propagate: no

  db_logger:
    level: DEBUG
    handlers: [console, db_handler]
    propagate: no

  ex_logger:
    level: DEBUG
    handlers: [ex_handler]
    propagate: no

  test_logger:
    level: DEBUG
    handlers: [test_handler]
    propagate: no

root:
  level: WARNING
  handlers: [console]
